### ISSUE TITLE
Sample code build errors.

### ISSUE THREAD

**Issue by jbum-digisynd** [cinder/Cinder-Kinect#1]
Building the sample code on OSX, I noticed a few issues which appear to be due to an out-of-date header file, starting with this one:

1) The kinectBasicApp.cpp initializes the kinect with this line:

```
mKinect = Kinect( Kinect::Device() ); // the default Device implies the first Kinect connected
```

This method appears supported in kinect.cpp, but the header file doesn't appear to support the devices method - it provides the following two constructors:

```
Kinect() {}
Kinect( int deviceIndex );
```

**Comment by andrewfb** [comment]
Sorry about that - should be fixed now.

**Comment by jbum-digisynd** [comment]
Cool!  Works great now. :)  Thanks for contributing this!
